### ISSUE TITLE
Gist token is not SIMPLE enough

### ISSUE THREAD

**Issue by lijunle** [fourcels/atom-package-sync#2]
Hi, thanks for providing an easy to use package to sync package between computers.

However, github token is only saw once then hidden. It means, I need to copy the token to somewhere and copy it when I am using a new Atom.

The best way is to use a server storage. Other ways are to give multiple method to store the list (jsfiddle, pastebin, etc.)

Any idea about this?

**Comment by fourcels** [comment]
You can generate new `token`, then reuse `gist id`

**Comment by lijunle** [comment]
Oh, get it!
